// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtwiaSnZukuYq-xhXp9URRZCgyRHwtgPQ',
    appId: '1:691242842102:web:55976229d83d5267b839d7',
    messagingSenderId: '691242842102',
    projectId: 'auth-77079',
    authDomain: 'auth-77079.firebaseapp.com',
    storageBucket: 'auth-77079.appspot.com',
    measurementId: 'G-F29G99E4WT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJFBdG3HCHJNPAJ9xKbWDdpByHHN3csyQ',
    appId: '1:691242842102:android:3b48aaba1cfa2629b839d7',
    messagingSenderId: '691242842102',
    projectId: 'auth-77079',
    storageBucket: 'auth-77079.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMOFYWvlYRlZwuIK6PHJVthFFEBVg8hG4',
    appId: '1:691242842102:ios:f6485afc213fc277b839d7',
    messagingSenderId: '691242842102',
    projectId: 'auth-77079',
    storageBucket: 'auth-77079.appspot.com',
    iosClientId: '691242842102-0rapmdhh02plqjrtvi8f80404kpojn15.apps.googleusercontent.com',
    iosBundleId: 'com.example.authenticationFfm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMOFYWvlYRlZwuIK6PHJVthFFEBVg8hG4',
    appId: '1:691242842102:ios:35a4f72e3be7bcb0b839d7',
    messagingSenderId: '691242842102',
    projectId: 'auth-77079',
    storageBucket: 'auth-77079.appspot.com',
    iosClientId: '691242842102-eect1qm0i5oclttvvpqgdvppstrmhaih.apps.googleusercontent.com',
    iosBundleId: 'com.example.authenticationFfm.RunnerTests',
  );
}
